insert into cities values (null, 'Buenos Aires', ‘Argentina Standard Time')
insert into cities values (null, 'Auckland', 'New Zealand Standard Time')
insert into cities values (null, 'London', 'Greenwich Standard Time')
insert into cities values (null, 'Paris', 'W. Europe Standard Time')
insert into cities values (null, 'New York', 'Eastern Standard Time')
insert into cities values (null, 'Tokyo', 'Tokyo Standard Time')
insert into cities values (null, 'San Francisco', 'Pacific Standard Time')
insert into cities values (null, 'Asuncion', 'Paraguay Standard Time')
insert into cities values (null, 'San Pablo', 'Central Brazilian Standard Time')
insert into cities values (null, 'Sidney', 'E. Australia Standard Time')
